#ifndef CONSTANTS_H
#define CONSTANTS_H

const int TRITET_TRUE = 1;
const int TRITET_FALSE = 0;
const int TRITET_SUCCESS = 0;
const int TRITET_ERROR_NULL_DATA = 10;
const int TRITET_STRING_CONCAT_ERROR = 20;
const int TRITET_ERROR_NULL_INPUT_DATA = 1000;
const int TRITET_ERROR_NULL_OUTPUT_DATA = 2000;
const int TRITET_ERROR_NULL_POINT_LIST = 3000;
const int TRITET_ERROR_NULL_SEGMENT_LIST = 4000;
const int TRITET_ERROR_NULL_REGION_LIST = 5000;
const int TRITET_ERROR_NULL_HOLE_LIST = 6000;
const int TRITET_ERROR_INVALID_POINT_INDEX = 300;
const int TRITET_ERROR_INVALID_SEGMENT_INDEX = 400;
const int TRITET_ERROR_INVALID_REGION_INDEX = 500;
const int TRITET_ERROR_INVALID_HOLE_INDEX = 600;

#endif  // CONSTANTS_H
