name: Test & Coverage
on: [pull_request, push]
jobs:
  test_and_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Libraries
        run: |
          sudo apt-get update -y && sudo apt-get install -y build-essential
      - name: Run tests
        run: |
          RUST_BACKTRACE=1 cargo test -- --nocapture
